### ISSUE TITLE
ویراستاری و رفع ایرادات نگارشی برای چاپ

### ISSUE THREAD

**Issue by sayjeyhi** [Mariotek/reactjs-persian-interview-questions#29]
## status

Pick one of these ranges and add a comment here, then start reading and correcting that range.

- [x] 0 - 20
- [x] 20 - 40
- [x] 40 - 60
- [x] 60 - 80
- [x] 80 - 100
- [x] 100 - 120
- [x] 120 - 140
- [x] 140 - 160
- [x] 160 - 180
- [x] 180 - 200
- [x] 200 - 220
- [x]  240 - 240
- [x]  240 - 260
- [x]  260 - 280
- [x]  280 - 300
- [x]  300 - 320
- [x]  320 - 324

**Comment by mehdirahimi** [comment]
I am the first one :)
Zero to Twenty

**Comment by sayjeyhi** [comment]
<div dir="rtl" align="right">
مرسی مهدی جان- رفیق قدیمی :)

مرسی - فقط یه چیزی رو میخواییم مدنظر داشته باشیم . اینکه میخواییم سعی کنیم ادبیات خیابونی و محاوره‌ای داشته باشیم توی این کتاب

چون https://github.com/Mariotek/reactjs-persian-interview-questions/pull/30 رو دیدم که روی افعال هم تصحیح زدی 
ولی به نظرت همین ادبیات صمیمی و محاوره‌ای باشه بهتر نیست؟
</div>

**Comment by mehdirahimi** [comment]
> مرسی مهدی جان- رفیق قدیمی :)
> مرسی - فقط یه چیزی رو میخواییم مدنظر داشته باشیم . اینکه میخواییم سعی کنیم ادبیات خیابونی و محاوره‌ای داشته باشیم توی این کتاب
> 
> چون #30 رو دیدم که روی افعال هم تصحیح زدی
> ولی به نظرت همین ادبیات صمیمی و محاوره‌ای باشه بهتر نیست؟

اتفاقا میخواستم ازت بپرسم که قراره محاوره ای باشه یا نه. چون تو راهنمای مشارکت نوشته بودی در موردش
هر چند که به نظر من ادبیات محاوره ای تو حالت بلاگی فوق العاده جذابه ولی به شکل چاپی به نظرم از ارزش کار کم میکنه
به هر حال شکل محاوره ای میتونه تجربه خوبی باشه. امتحانش کن

تصحیح شد 
[#32 ](https://github.com/Mariotek/reactjs-persian-interview-questions/pull/32)

**Comment by sayjeyhi** [comment]
<div dir="rtl">

[این افزونه کروم](https://chrome.google.com/webstore/detail/weava-highlighter-pdf-web/cbnaodkpfinfiipjblikofhlhlcickei
) خیلی میتونه توی سریع‌تر شدن مطالعه و ویراستاری کمک کنه

</div>

**Comment by sayjeyhi** [comment]
<div dir="rtl">
تا سوال ۱۰۰ ویراستاری شد و پوش شد
</div>

**Comment by sayjeyhi** [comment]
تا ۱۴۰ پیش رفتم

**Comment by sayjeyhi** [comment]
تا ۲۲۰
