### ISSUE TITLE
اشکال در مثال سوال 3

### ISSUE THREAD

**Issue by westernal** [Mariotek/reactjs-persian-interview-questions#36]
سلام، مثال سوال 3 هر دو کلاس هستند.

### عکس

![image](https://github.com/Mariotek/reactjs-persian-interview-questions/assets/79543272/ef119dff-eee0-44fd-845c-a4aa518313cc)

### مثال اصلی
```
export default function App() {
  return (
      <h1 className="greeting">{"Hello, this is a JSX Code!"}</h1>
  );
}
```

**Comment by sayjeyhi** [comment]
Hi, 
If you can fix this, PRs are very welcome here :)
